export enum Genre {
    mmorpg = "mmorpg",
    shooter = "shooter",
    strategy = "strategy",
    moba = "moba",
    racing = "racing",
    sports = "sports",
    social = "social",
    sandbox = "sandbox",
    openWorld = "open-world",
    survival = "survival",
    pvp = "pvp",
    pve = "pve",
    pixel = "pixel",
    voxel = "voxel",
    zombie = "zombie",
    turnBased = "turn-based",
    firstPerson = "first-person",
    thirdPerson = "third-Person",
    topDown = "top-down",
    tank = "tank",
    space = "space",
    sailing = "sailing",
    sideScroller = "side-scroller",
    superhero = "superhero",
    permadeath = "permadeath",
    card = "card",
    battleRoyale = "battle-royale",
    mmo = "mmo",
    mmofps = "mmofps",
    mmotps = "mmotps",
    _3d = "3d",
    _2d = "2d",
    anime = "anime",
    fantasy = "fantasy",
    sciFi = "sci-fi",
    fighting = "fighting",
    actionRPG = "action-rpg",
    action = "action",
    military = "military",
    martialArts = "martial-arts",
    flight = "flight",
    lowSpec = "low-spec",
    towerDefense = "tower-defense",
    horror = "horror",
    mmorts = "mmorts",
}


export enum Platform {
    PCWindows = "PC (Windows)",
    PCWindowsWebBrowser = "PC (Windows), Web Browser",
    WebBrowser = "Web Browser",
}
